### ISSUE TITLE
Error en la busqueda de los Smart Browser

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/backend#16]
En el criterio de busqueda se agregan 2 parametros y se realiza la busqueda pero el servidor parece no filtrar los resultados de manera correcta

### GIF Version ZK
![zk](https://user-images.githubusercontent.com/45974454/170520348-d2f4a218-019f-4f56-b71b-2e897594ba8d.gif)

### GIF Version UI
![errror](https://user-images.githubusercontent.com/45974454/170520499-27ddec54-cf3f-4ae8-8d1f-77b3017de334.gif)

**Comment by EdwinBetanc0urt** [comment]
Solucionado en https://github.com/solop-develop/backend/pull/10
