### ISSUE TITLE
Error en los Lookup

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/backend#17]
En el Smart Browser _**Procesar Órdenes en Lote**_ cuando se agrega el parametro _**Tipo Documento Destino**_  arroja el siguiente error 
### Error
`Pestaña Cláusula Where SQL Unparseable\nPestaña Cláusula Where SQL Unparseable`

### GIf 
![error-lookup](https://user-images.githubusercontent.com/45974454/170521526-b6ae0f59-a937-42dc-aad2-0d15ab8ec261.gif)

**Comment by EdwinBetanc0urt** [comment]
Solucionado en https://github.com/solop-develop/backend/pull/14
